<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tw_cookie"
 *
 * Auto generated by Extension Builder 2018-06-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'tollwerk Cookie Consent',
    'description' => 'Provide a Cookie Consent Banner',
    'category' => 'plugin',
    'author' => 'Klaus Fiedler',
    'author_email' => 'klaus@tollwerk.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.1.0',
    'constraints' => array(
        'depends' => array(
            'typo3' => '7.1.0-8.99.99',
        ),
        'conflicts' => array(),
        'suggests' => array(),
    ),
);
